### PR TITLE
Dependency Updates (Ready)

### PR DESCRIPTION
**Pull request by CDAGaming**
This PR Patches a .gitignore error where some files generated by IDEA make it past The ignore file, as well as updating Forge and MCP Mappings, and HWYLA also

### CODE REVIEW

**Comment by CDAGaming** [comment]
Clear to Merge now :)

**Comment by darkhax** [comment]
This is a very weird PR. You make a lot of changes that go beyond the initial scope of the PR, and some style changes that are not consistent with the rest of the mod, and my other mods. I don't want your work to go to waste so I am still going to merge, just something to keep in mind.

**Comment by CDAGaming** [comment]
Yea, I think most changes were from the code cleanup, which is a command included in IntelliJ. It was also Optional, but I included it just for simplicity. Next time, I'll keep it in mind and I should've also asked if you'd want that cleanup with this PR or rather in a seperate PR

**Comment by CDAGaming** [comment]
There was one more thing I was going to include in the PR, which was an Upgrade to Gradle from 4.2/4.2.1 to 4.3-bin, so that will be coming later today, just a heads up

**Pull request merged**
